//USER
export const SET_USER = "SET_USER";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

//DESTINATIONS
export const FETCH_DESTINATIONS = "FETCH_DESTINATIONS";

//FLIGHTS
export const FETCH_FLIGHTS = "FETCH_FLIGHTS";

//BOOKING
export const CREATE_BOOKING = "CREATE_BOOKING";
export const SET_DETAILS = "SET_DETAILS";
export const SET_FLIGHTS = "SET_FLIGHTS";

//TRAVELCLASSES
export const FETCH_TRAVELCLASSES = "FETCH_TRAVELCLASSES";
